name: update_address
description: "주소 찾기 (또는 주소 자동 완성) 기능과 주소의 위경도 좌표를 찾는 기능을 제공합니다."
version: 0.0.1
homepage: https://github.com/thruthesky/update_address

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
